version: "3.8"

services:
  bittle:
    image: bittle-rl
    build:
      context: .  # Adjust if your Dockerfile is in a subfolder
      dockerfile: Dockerfile
    container_name: bittle-sim
    network_mode: "host"  # Needed for DISPLAY access on Linux
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/nvidia:$LD_LIBRARY_PATH
      - OMNI_KIT_ALLOW_ROO=1

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ~/.cache/ov:/root/.cache/ov:rw
      - ~/.nucleus:/root/.nucleus:rw

      # - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY

    runtime: nvidia  # For older Docker versions. Use "deploy" below for modern compose
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
            
    entrypoint: ["/entrypoint.sh"]
    #entrypoint : ["/bin/bash", "-c", "source /entrypoint.sh && exec python3 alpha/exts/customView/customView/pyqt_interface.py"]
